# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://polyglots.us
title: PolyGLOTS
email: contact@polyglots.us
author: Magdalena Rzemieniewska
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 Polyglots.us. All Rights Reserved.'
credits: 'office: 250 McAdoo Dr. 95630 Folsom, CA <br /> phone: (279) 321-8106'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: e-mail
    icon: envelope
    url: mailto:magdal.paczkowska@gmail.com
  - title: phone
    icon: phone
    url: \#location
  - title: office
    icon: home
    url: \#location
